#!/bin/bash
./configure --prefix=/opt/f8n/nginx --with-rtsig_module --with-select_module --with-file-aio --with-http_ssl_module --with-http_spdy_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module --with-http_image_filter_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_auth_request_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_stub_status_module --with-mail --with-mail_ssl_module --with-pcre --with-libatomic
CPU_N=`grep processor /proc/cpuinfo | wc -l`
make -j $(($CPU_N + 1))
make install DESTDIR=$DESTDIR
